

= Documentation Technique SAE-ALT-S3-Dev-23-24-LocURa

== CHAROUKI Aymen		

== PAGNUCCO Nathan

== FONTANILLES Alexi

== PICUIRA Tanguy

= Groupe 4

= Années 2023-2024

=== Sommaire

:sectnums:
toc::[Sommaire]


== Présentation du projet

===  *Contexte Générale*

La plateforme de recherche LocURa4IoT, hébergée à l’IUT de Blagnac, utilise actuellement un outil de visualisation des positions de tags mobiles dans l’environnement du laboratoire. Cette visualisation est essentielle à des fins de compréhension des résultats de recherche ainsi que pour des démonstrations pédagogiques. Concrètement, l'outil représente les différents éléments du système de localisation, tels que les ancres/références, les tags/mobiles, les murs, etc., sur une carte interactive.

=== Objectif du Projet :
L'objectif principal de ce projet est d'améliorer l'interface actuelle en ajoutant des fonctionnalités cruciales pour une expérience utilisateur plus avancée. Ces fonctionnalités comprennent la possibilité d'activer/désactiver certains éléments à afficher, la sélection d'éléments avec des options de filtrage, et l'affichage de la trace des mobiles, incluant les mouvements et l'historique des positions.

=== Technologies Utilisées :
Les technologies au cœur de ce projet sont le web, JavaScript (JS), Scalable Vector Graphics (SVG), MQTT (Message Queuing Telemetry Transport), et les WebSockets. Ces technologies offrent une base solide pour la création d'une interface interactive et en temps réel.

==  Cas d'Utilisation Global

Cette application, conçue exclusivement pour les chercheurs du laboratoire, propose les cas d'utilisation suivants :

* Consulter les Mesures de Distance
** Consulter les mesures de distance sur le site web pour visualiser les distances entre les points dans le laboratoire.

* Accéder à l'Historique des Points
** Accéder à la base de données pour consulter l'historique de chaque point. Analyser les données passées pour obtenir un aperçu temporel.

* Visualiser les Mesures de Distance
** Visualiser les mesures de distance sur le site web pour une représentation graphique claire des distances entre les points dans le laboratoire.

* Explorer la Localisation des Capteurs
** Accéder au plan et à la localisation des capteurs sur le site web pour améliorer la visualisation des expériences.

* Filtrer les Layers pour Localiser les Objets Connectés
** Filtrer l'affichage des layers sur le site web pour localiser les étages des objets connectés dans le laboratoire.

* Filtrer l'Affichage des IDs Objets
** Filtrer l'affichage des IDs objets sur le site web pour identifier des informations spécifiques dans le laboratoire.

* Consulter le Contenu du Site Web
** Accéder au site web pour consulter son contenu, y compris les informations, résultats de recherche et démonstrations.

== Diagrammes des classes 
Celui-ci présente le diagramme des classes de notre projet : 
https://github.com/IUT-Blagnac/SAE-ALT-S3-Dev-23-24-LocURa-Equipe-3A04/blob/master/Projet/diagrammeClasse.png
