:toc-title: Sommaire
:toc: macro
:toclevels: 3

= Documentation Utilisateur

== Sommaire


:sectnums:
toc::[Sommaire]

== Présentation Application

===  *Contexte Générale*
****
La localisation d'engins immobiles ou mobiles à l'intérieur des entrepots est un enjeu de plus en plus grandissant. En effet, les entrepots sont de plus en plus grands et les engins mobiles de plus en plus nombreux. Il est donc nécessaire de pouvoir localiser ces engins afin de pouvoir les retrouver rapidement et de pouvoir optimiser leur utilisation. Pour faire ces recherche, une équipe de chercheurs est présentes à l'IUT de Blagnac dans une salle prévu à cette effet contenant plus de 5à capteurs. Ces capteurs sont répartis dans la salle et permettent de simuler la localisation des engins avec la présence d'un rail simulant un objet mobiles. Pour voir leur localisation les chercheurs utilisent un site web qui affichent en temps réel la position des capteurs. Cependant, ce site web est assez ancien et peut être mieux optimiser. 
****

 === *Sujet et Présentation*
****
Dans ce contexte nous avons pour mission de créer une application web permettant de visualiser la position des capteurs en temps réel. Cette application devra être plus ergonomique et plus facile d'utilisation que l'application actuelle. Elle devra également permettre de visualiser l'historique des positions des capteurs. Pour cela nous avons décidé de créer une application web en utilisant du JavaScript pour pouvoir avoir des page qui se mettent à jour en temps réel. Cette application devra être relié à une base de données qui contiendra les informations des capteurs. Pour cela nous avons décidé d'utiliser une base de données MariaDB. Il y a également les fonctionnalités présentes sur l'ancienne application, c'est à dire la possibilité de visualiser ou non les cercles représentants la vision des capteurs.
****

== Installation
****
Pour pouvoir utiliser le site web il y a juste besoin d'une connexion internet et d'un navigateur web. Il n'y a pas besoin d'installer de logiciel supplémentaire.
****

== Fonctionnalités de l'application
