:toc-title: Sommaire
:toc: macro
:toclevels: 3

= Documentation Utilisateur SAE-ALT-S3-Dev-23-24-LocURa

 CHAROUKI Aymen		

 PAGNUCCO Nathan

 FONTANILLES Alexi

 PICUIRA Tanguy

 Groupe 4

 Années 2023-2024 



:sectnums:
toc::[Sommaire]

== Présentation Application

===  *Contexte Général*

****
Nom du projet : LocURa4IoT

Lien : https://locura4iot.irit.fr[LocURa4IoT]
****

****
La localisation d'engins immobiles ou mobiles à l'intérieur des entrepots est un enjeu de plus en plus grandissant. En effet, les entrepots sont de plus en plus grands et les engins mobiles de plus en plus nombreux. Il est donc nécessaire de pouvoir localiser ces engins afin de pouvoir les retrouver rapidement et de pouvoir optimiser leur utilisation. Pour faire ces recherches, une équipe de chercheurs est présentes à l'IUT de Blagnac dans une salle prévu à cet effet contenant plus de 5à capteurs. Ces capteurs sont répartis dans la salle et permettent de simuler la localisation des engins avec la présence d'un rail simulant un objet mobiles. Pour voir leur localisation, les chercheurs utilisent un site web qui affiche en temps réel la position des capteurs. Cependant, ce site web est assez ancien et peut être mieux optimisé.
****

=== *Sujet et Présentation*

****
Dans ce contexte, nous avons pour mission de créer une application web permettant de visualiser la position des capteurs en temps réel. Cette application devra être plus ergonomique et plus facile d'utilisation que l'application actuelle. Elle devra également permettre de visualiser l'historique des positions des capteurs. Pour cela, nous avons décidé de créer une application web en utilisant du JavaScript pour pouvoir avoir des pages qui se mettent à jour en temps réel. Cette application devra être reliée à une base de données qui contiendra les informations des capteurs. Pour cela, nous avons décidé d'utiliser une base de données MariaDB. Il y a aussi les fonctionnalités présentes sur l'ancienne application, c'est-à-dire la possibilité de visualiser ou non les cercles représentants la vision des capteurs.
****

=== Installation

****
Pré-requis : 

* Docker sur le serveur
* La release situé https://github.com/IUT-Blagnac/SAE-ALT-S3-Dev-23-24-LocURa-Equipe-3A04/tree/master/Projet/app[ici]

Pour installer le docker sur un serveur il faut

- Lancer le create.bat si on est dans un serveur windows
- Lancer le create.sh si on est dans un serveur unix

⚠️ ATTENTION ⚠️

Pour que le serveur puisse correctement récupérer les données MQTT il faut s'assurer que le port 1883 est ouvert sur le pare feu de la connexion

****

== Fonctionnalités

=== Fonctionnalité de l'application - Sprint 1

L'application représente une maquette simpliste de test qui permet de vérifier la connexion au brocker MQTT, le placement de points sur une carte.

Il n'y a pas encore de fonctionnalités réellement disponibles pour l'utilisateur.

=== Fonctionnalité de l'application - Sprint 2

Ajouts :

L'application permet de visualiser les capteurs sur une carte dès le lancement de la page. Chaque point est cliquable et une pop-up s'ouvre affichant les informations du noeud cliqué. Dans le header, il est possible de choisir les points à afficher selon son ID. Un historique des positions des capteurs est également disponible.

=== Fonctionnalité de l'application - Sprint 3

Ajouts :

Ajout des scripts launch.sh (Linux) et launch.bat (Windows) pour lancer le serveur Web et le base de données.
Au lancement de la page, l'étage 1 est affiché avec les points de l'étage 1. Il est possible de changer d'étage grâce à un menu déroulant: les étages se superposent de manière lisible et si aucun étage est selectionné, aucun noeud est affiché. La fonctionnalité étage n'est pas complètement implémentée. En effet, actuellement il existe aucun cas réel d'utilisation donc il n'est pas vraiment possible d'implémenter la fonctionnalité mais un exemple est fourni et il sera possible à l'avenir de modifier ces exemples à la guise. Il est également possible de choisir les points à afficher selon leur ID, leur UID le DWM ou grâce à la recherche de l'ID. Un historique des positions des capteurs est également disponible. Le contenu de la base de données est accessible grâce au bouton DEBUG dans le header. Une lumière clignotant indique l'état de la connexion au broker MQTT: si la lumière est rouge la connexion est perdue, si la lumière est verte la connexion est établie. Il est également possible de visualiser le ranging des capteurs grâce au bouton "Activer cercles" dans le header, choisir de remplir les cercles et activer les lignes représentant la vision des capteurs.
Parfois, il est impossible de savoir s'il y a une erreur avec les scripts en arrière-plan (comme connexionMQTT.php) il faut donc exécuter la commande ps -ef dans le serveur pour voir si les scripts sont bien lancés et fonctionnels.