:toc-title: Sommaire
:toc: macro
:toclevels: 3

= Documentation Utilisateur SAE-ALT-S3-Dev-23-24-LocURa

 CHAROUKI Aymen		

 PAGNUCCO Nathan

 FONTANILLES Alexi

 PICUIRA Tanguy

 Groupe 4

 Années 2023-2024 



:sectnums:
toc::[Sommaire]

== Présentation Application

===  *Contexte Général*

****
Nom du projet : LocURa4IoT

Lien : https://locura4iot.irit.fr[LocURa4IoT]
****

****
La localisation d'engins immobiles ou mobiles à l'intérieur des entrepots est un enjeu de plus en plus grandissant. En effet, les entrepots sont de plus en plus grands et les engins mobiles de plus en plus nombreux. Il est donc nécessaire de pouvoir localiser ces engins afin de pouvoir les retrouver rapidement et de pouvoir optimiser leur utilisation. Pour faire ces recherches, une équipe de chercheurs est présentes à l'IUT de Blagnac dans une salle prévu à cet effet contenant plus de 5à capteurs. Ces capteurs sont répartis dans la salle et permettent de simuler la localisation des engins avec la présence d'un rail simulant un objet mobiles. Pour voir leur localisation, les chercheurs utilisent un site web qui affiche en temps réel la position des capteurs. Cependant, ce site web est assez ancien et peut être mieux optimisé.
****

=== *Sujet et Présentation*

****
Dans ce contexte, nous avons pour mission de créer une application web permettant de visualiser la position des capteurs en temps réel. Cette application devra être plus ergonomique et plus facile d'utilisation que l'application actuelle. Elle devra également permettre de visualiser l'historique des positions des capteurs. Pour cela, nous avons décidé de créer une application web en utilisant du JavaScript pour pouvoir avoir des pages qui se mettent à jour en temps réel. Cette application devra être reliée à une base de données qui contiendra les informations des capteurs. Pour cela, nous avons décidé d'utiliser une base de données MariaDB. Il y a aussi les fonctionnalités présentes sur l'ancienne application, c'est-à-dire la possibilité de visualiser ou non les cercles représentants la vision des capteurs.
****

=== Installation

****
Pré-requis : 

* Docker sur le serveur
* La release située https://github.com/IUT-Blagnac/SAE-ALT-S3-Dev-23-24-LocURa-Equipe-3A04/tree/master/Projet/app[ici]

Pour installer le docker sur un serveur il faut

- Lancer le create.bat si on est dans un serveur windows
- Lancer le create.sh si on est dans un serveur unix

Pour lancer le docker il faut utiliser :

- Le script launch.bat sur windows
- Le script launch.sh sur linux 

Ce script permet de lancer le script PHP qui récupère les données MQTT et écrit les données en base.

⚠️ ATTENTION ⚠️

Pour que le serveur puisse correctement récupérer les données MQTT il faut s'assurer que le port 1883 est ouvert sur le pare feu de la connexion, si le site ne fonctionne pas bien il est utile de vérifier si le script connexionMQTT.php est bien en état de marche

Pour se connecter au site il suffit d'aller sur le port 8080 de l'ip de la machine qui le host

****

== Fonctionnalités

Le site permet de visualiser facilement la carte d'un étage et les capteurs qui y sont présents. Dans le header du site on peut : 

- Voir et selectionner les différents étages (non implémenté)
- Selectionner les capteurs à afficher en fonction de leur ID, leur UID le DWM ou grâce à la recherche de l'ID, avec la barre de recherche ou dans le dropdown
- Accéder à la page de DEBUG qui permet de voir le contenu des bases de données
- Choisir l'id affichée sur chaque capteur entre les trois différentes
- Activer ou désactiver les cercles représentant les données de ranging des capteurs
- Activer ou désactiver les lignes représentant la vision des capteurs
- Acviter ou désactiver le remplissage des cercles

Dans la carte on peut voir les capteurs et leur positions, ainsi qu'intéragir avec eux pour voir toutes les informations stockées dans leur Setup.

Dans la page de debug on peut voir le contenu des bases de données à un instant fixé, ce qui permet de voir un historique des données actuelles.
